#!/bin/sh

id=`id | cut -f1 -d'('`
if [ $id != "uid=0" ]
then
	echo
	echo "You must be root to run this script"
	echo
	exit
fi

os=`uname`

if [ $os = "OpenBSD" ]
then
	pkg_add git
else
	apt install git
fi

cd /home
git clone --depth=1 https://github.com/iudx/iudx-sub-ca

cd iudx-sub-ca

if [ $os = "OpenBSD" ]
then
	./setup.openbsd
else
	./setup.docker
fi
